"""baseline schema

Revision ID: 0964e5b227e3
Revises: 
Create Date: 2026-09-08 11:44:56.281656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0964e5b227e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('alert_level', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('forecast_horizon_hours', sa.Integer(), nullable=True),
    sa.Column('factors', sa.String(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_table('fire_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('acq_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('frp', sa.Float(), nullable=True),
    sa.Column('satellite', sa.String(), nullable=True),
    sa.Column('daynight', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fire_readings_id'), 'fire_readings', ['id'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('forecast_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('horizon_hours', sa.Integer(), nullable=False),
    sa.Column('pm25_pred', sa.Float(), nullable=True),
    sa.Column('pm10_pred', sa.Float(), nullable=True),
    sa.Column('o3_pred', sa.Float(), nullable=True),
    sa.Column('no2_pred', sa.Float(), nullable=True),
    sa.Column('so2_pred', sa.Float(), nullable=True),
    sa.Column('co_pred', sa.Float(), nullable=True),
    sa.Column('aqi_pred', sa.Integer(), nullable=True),
    sa.Column('aqi_category', sa.String(), nullable=True),
    sa.Column('dominant_pollutant', sa.String(), nullable=True),
    sa.Column('inversion_detected', sa.Integer(), nullable=True),
    sa.Column('inversion_strength', sa.Float(), nullable=True),
    sa.Column('pbl_height', sa.Float(), nullable=True),
    sa.Column('coupling_stability', sa.Float(), nullable=True),
    sa.Column('coupling_mode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_forecast_station_time', 'forecasts', ['station_id', 'forecast_timestamp'], unique=False)
    op.create_index(op.f('ix_forecasts_id'), 'forecasts', ['id'], unique=False)
    op.create_table('model_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('pollutant', sa.String(), nullable=False),
    sa.Column('horizon_hours', sa.Integer(), nullable=False),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('r2', sa.Float(), nullable=True),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('test_period_start', sa.DateTime(), nullable=True),
    sa.Column('test_period_end', sa.DateTime(), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_metrics_id'), 'model_metrics', ['id'], unique=False)
    op.create_table('pollution_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pm25', sa.Float(), nullable=True),
    sa.Column('pm10', sa.Float(), nullable=True),
    sa.Column('o3', sa.Float(), nullable=True),
    sa.Column('no2', sa.Float(), nullable=True),
    sa.Column('so2', sa.Float(), nullable=True),
    sa.Column('co', sa.Float(), nullable=True),
    sa.Column('aqi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pollution_station_time', 'pollution_readings', ['station_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_pollution_readings_id'), 'pollution_readings', ['id'], unique=False)
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_stations_id'), 'stations', ['id'], unique=False)
    op.create_table('weather_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('pressure_msl', sa.Float(), nullable=True),
    sa.Column('surface_pressure', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Float(), nullable=True),
    sa.Column('precipitation', sa.Float(), nullable=True),
    sa.Column('cloud_cover', sa.Float(), nullable=True),
    sa.Column('pbl_height', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_weather_station_time', 'weather_readings', ['station_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_weather_readings_id'), 'weather_readings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_readings_id'), table_name='weather_readings')
    op.drop_index('idx_weather_station_time', table_name='weather_readings')
    op.drop_table('weather_readings')
    op.drop_index(op.f('ix_stations_id'), table_name='stations')
    op.drop_table('stations')
    op.drop_index(op.f('ix_pollution_readings_id'), table_name='pollution_readings')
    op.drop_index('idx_pollution_station_time', table_name='pollution_readings')
    op.drop_table('pollution_readings')
    op.drop_index(op.f('ix_model_metrics_id'), table_name='model_metrics')
    op.drop_table('model_metrics')
    op.drop_index(op.f('ix_forecasts_id'), table_name='forecasts')
    op.drop_index('idx_forecast_station_time', table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_fire_readings_id'), table_name='fire_readings')
    op.drop_table('fire_readings')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###