"""Phase-1 observation schema

Renames the observation tables to their Phase-1 names and adds the
Phase-1 fields:

  * pollution_readings  -> pollution_observations (real FK to stations.id;
    UNIQUE (station_id, timestamp) already present via b9c9f4d1a7e2 and kept)
  * weather_readings    -> weather_observations (adds latitude, longitude,
    pressure; existing station-keyed columns are preserved for the app)

Revision ID: d4a1e4c9f0b2
Revises: b9c9f4d1a7e2
Create Date: 2026-09-12 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd4a1e4c9f0b2'
down_revision: Union[str, None] = 'b9c9f4d1a7e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Rename the two observation tables to the Phase-1 names. Postgres carries
    # each table's indexes and the uq_pollution_station_ts unique constraint
    # over to the new name automatically.
    op.rename_table('pollution_readings', 'pollution_observations')
    op.rename_table('weather_readings', 'weather_observations')

    # Drop the autogenerated per-column id indexes so they are recreated with
    # Phase-1 names (ix_<table>_id) and the metadata stays in sync.
    op.drop_index('ix_pollution_readings_id', table_name='pollution_observations')
    op.drop_index('ix_weather_readings_id', table_name='weather_observations')
    op.create_index(op.f('ix_pollution_observations_id'), 'pollution_observations', ['id'], unique=False)
    op.create_index(op.f('ix_weather_observations_id'), 'weather_observations', ['id'], unique=False)

    # Rename the PK constraints (and their backing indexes) to match.
    op.execute('ALTER TABLE pollution_observations RENAME CONSTRAINT pollution_readings_pkey TO pollution_observations_pkey')
    op.execute('ALTER TABLE weather_observations RENAME CONSTRAINT weather_readings_pkey TO weather_observations_pkey')

    # Rename the id sequences; Postgres rewrites the column defaults to match.
    op.execute('ALTER SEQUENCE pollution_readings_id_seq RENAME TO pollution_observations_id_seq')
    op.execute('ALTER SEQUENCE weather_readings_id_seq RENAME TO weather_observations_id_seq')

    # weather_observations gains the Phase-1 location + pressure fields.
    op.add_column('weather_observations', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('weather_observations', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('weather_observations', sa.Column('pressure', sa.Float(), nullable=True))

    # pollution_observations.station_id must reference stations.id.
    op.create_foreign_key(
        'fk_pollution_observations_station',
        'pollution_observations', 'stations',
        ['station_id'], ['id'],
    )


def downgrade() -> None:
    op.drop_constraint('fk_pollution_observations_station', 'pollution_observations', type_='foreignkey')
    op.drop_column('weather_observations', 'pressure')
    op.drop_column('weather_observations', 'longitude')
    op.drop_column('weather_observations', 'latitude')
    op.execute('ALTER SEQUENCE weather_observations_id_seq RENAME TO weather_readings_id_seq')
    op.execute('ALTER SEQUENCE pollution_observations_id_seq RENAME TO pollution_readings_id_seq')
    op.execute('ALTER TABLE weather_observations RENAME CONSTRAINT weather_observations_pkey TO weather_readings_pkey')
    op.execute('ALTER TABLE pollution_observations RENAME CONSTRAINT pollution_observations_pkey TO pollution_readings_pkey')
    op.drop_index(op.f('ix_weather_observations_id'), table_name='weather_observations')
    op.drop_index(op.f('ix_pollution_observations_id'), table_name='pollution_observations')
    op.rename_table('weather_observations', 'weather_readings')
    op.rename_table('pollution_observations', 'pollution_readings')
    op.create_index(op.f('ix_weather_readings_id'), 'weather_readings', ['id'], unique=False)
    op.create_index(op.f('ix_pollution_readings_id'), 'pollution_readings', ['id'], unique=False)