"""Alembic migration environment for AeroCast-NCR.

The database URL is resolved from:
  1. an optional `-x db_url=...` extra (recommended for CI),
  2. the DATABASE_URL environment variable,
  3. the app's settings (backend.app.config) as a final fallback.

Autogenerated revisions target the SQLAlchemy metadata in backend.app.models.
"""

import os
import sys
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# ensure the backend package is importable so the metadata below resolves
_backend_root = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "backend")
if _backend_root not in sys.path:
    sys.path.insert(0, _backend_root)

if config.attributes.get("configure_logger", True):
    pass

from app.database import Base  # noqa: E402
import app.models.db_models  # noqa: E402,F401  register tables on Base.metadata

target_metadata = Base.metadata


def _resolve_db_url() -> str:
    extra = config.get_main_option("db_url")
    if extra:
        return extra
    env_url = os.environ.get("DATABASE_URL")
    if env_url:
        return env_url
    from app.config import get_settings

    return get_settings().database_url


def run_migrations_offline() -> None:
    context.configure(
        url=_resolve_db_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
        url=_resolve_db_url(),
    )

    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()